[phases.setup]
nixPkgs = [
  "nodejs_20",
  "nspr", "nss", "atk", "cups", "libdrm", "libxkbcommon",
  "alsa-lib", "at-spi2-atk", "at-spi2-core",
  "xorg.libX11", "xorg.libXcomposite", "xorg.libXdamage",
  "xorg.libXext", "xorg.libXfixes", "xorg.libXrandr",
  "xorg.libxcb", "mesa", "expat", "pango", "cairo", "glib"
]

[phases.install]
cmds = ["npm install --omit=dev=false"]

[start]
cmd = "node server/app.js"
